modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="midnight"
version="${file.jarVersion}"
displayName="The Midnight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-midnight"
logoFile="logo.png"
authors="Cryptic Mushroom"
credits="Cipher Zero X, Jonathing, Shadew, Lachney, bagu_chan, gegy1000, Martacus, arthurbambous, Corail31, Endergized, Five (Paradiscal), MCVinnyq"
description='''The Midnight adds a new, mysterious and scary dimension to explore. It is a dimension of darkness, with light resonating from solely from the environment. You may choose to embark on a journey to this cold and alienated place, although you may unwillingly encounter a rifter and be dragged into this strange and hostile world...'''

[[dependencies.midnight]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.56,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.midnight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"

[[dependencies.midnight]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.4,)"
    ordering="BEFORE"
    side="CLIENT"
